services:
  spark-master:
    image: apache/spark-py:3.5.0
    container_name: spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*
      "
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark-py:3.5.0
    container_name: spark-worker-1
    environment:
      SPARK_NO_DAEMONIZE: "true"
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*
      "
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark-py:3.5.0
    container_name: spark-worker-2
    environment:
      SPARK_NO_DAEMONIZE: "true"
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*
      "
    depends_on:
      - spark-master
    networks:
      - spark-net

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    volumes:
      - ../workspace:/workspace
    ports:
      - "8888:8888"
    networks:
      - spark-net

networks:
  spark-net:
